name: 'confluence-readme-sync'
description: 'Copies the contents of a markdown file to a Confluence page'
branding:
  icon: upload-cloud
  color: blue
inputs:
  filepath:
    description: 'File path of the markdown file to sync, relative to the root of the repository - README.md by default'
    required: true
    default: '${{ github.workspace }}/README.md'
  url:
    description: 'Full URL of the Confluence page to sync with, including the https://'
    required: true
  username:
    description: 'Confluence username associated with token'
    required: true
  token:
    description: 'Confluence token for the user'
    required: true
  insert_start_text:
    description: 'HTML or text marking the start of the block to insert the markdown into'
    required: true
  insert_end_text:
    description: 'HTML or text marking the end of the block to insert the markdown into'
    required: true
  max_image_width:
    description: 'Maximum width for images in pixels (e.g., 800). Leave empty to use original size'
    required: false
    default: '800'
runs:
  using: 'docker'
  image: 'Dockerfile'